const data = {
    products: [
      {
        _id: '1',
        name: 'Black w/ gold',
        color: 'black',
        image: '/images/GEE_1.jpg',
        price: 190,
        brand: 'Lacoste',
        countInStock: 4,
        description: 'black colored flats with gold accent',
      },
      {
        _id: '2',
        name: 'Easy slip-on',
        color: 'black',
        image: '/images/GEE_2.jpg',
        price: 150,
        brand: 'Gee',
        countInStock: 6,
        description: 'easy to wear flats',
      },
      {
        _id: '3',
        name: 'White elegance',
        color: 'white',
        image: '/images/GEE_3.jpg',
        price: 180,
        brand: 'Lacoste',
        countInStock: 4,
        description: 'white colored office flats',
      },
      {
        _id: '4',
        name: 'Easy slip-on 2',
        color: 'black',
        image: '/images/GEE_4.jpg',
        price: 180,
        brand: 'Lacoste',
        countInStock: 2,
        description: 'easy to wear flats',
      },
      {
        _id: '5',
        name: 'Flesh',
        color: 'flesh',
        image: '/images/GEE_5.jpg',
        price: 170,
        brand: 'Gee',
        countInStock: 4,
        description: 'flesh/nude colored flats',
      },
      {
        _id: '6',
        name: 'Open',
        color: 'black',
        image: '/images/GEE_6.jpg',
        price: 180,
        brand: 'Gee',
        countInStock: 9,
        description: 'fully revealed',
      },
    ],
  };
  export default data;